[package]
name = "min_Async_runtiame"
version = "0.1.0"
edition = "2021"

[dependencies]
mio = { version = "1.0.2", features = ["net", "os-ext", "os-poll"] }
nix = { version = "0.29.0", features = ["time"] }
dashmap = "6.1.0"
